"""A0 backbone comparison against Kashif et al. Table 3 (guide section 5.1).

Validation-partition only. These runs are a reproduction check, not a
selection step: every arm's configuration was fixed at `freeze-v1` and
nothing here can change it.

A backbone is flagged DEGENERATE when its balanced accuracy is exactly
0.5 with recall 1.0 -- it emits the majority class for every image, so
its "accuracy" is just the base rate (41/62 = 0.6613) and must not be
read as performance.

Writes results/a0_backbones.md and figures/tab_a0_backbones.tex.

Run: python src/a0_table.py
"""
from __future__ import annotations

import csv
import json
import statistics as st
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
RESULTS = REPO / "results"
FIGS = REPO / "figures"

# Kashif et al. (2026) Table 3, transcribed from the source PDF p.10 and
# recorded in configs/grid.yaml. Their protocol and split differ from
# ours, so these are context, not a like-for-like target.
KASHIF = {"cnn_scratch": 0.7743, "vgg16": 0.7684, "inceptionv3": 0.7661,
          "mobilenetv2": 0.7836, "mobilenetv3small": 0.7216}
ORDER = ["mobilenet", "cnn_scratch", "vgg16", "inceptionv3",
         "mobilenetv2", "mobilenetv3small"]
BASE_RATE = 41 / 62


def best_per_backbone() -> dict:
    rows = [r for r in csv.DictReader(
        (RESULTS / "all_runs.csv").open(encoding="utf-8"))
        if r["phase"] == "tuning"]
    g = defaultdict(list)
    for r in rows:
        g[(r["backbone"], r["optimizer"], r["learning_rate"])].append(r)

    best = {}
    for (b, o, lr), v in g.items():
        if len(v) < 3:
            continue
        acc = [float(x["acc"]) for x in v]
        m = st.mean(acc)
        if b not in best or m > best[b]["acc_mean"]:
            best[b] = {
                "backbone": b, "optimizer": o, "learning_rate": float(lr),
                "n_seeds": len(v),
                "acc_mean": m, "acc_sd": st.stdev(acc),
                "bal_acc": st.mean(float(x["bal_acc"]) for x in v),
                "auc": st.mean(float(x["auc"]) for x in v),
                "recall": st.mean(float(x["rec"]) for x in v),
                "f1": st.mean(float(x["f1"]) for x in v),
            }
    for b, d in best.items():
        d["degenerate"] = bool(abs(d["bal_acc"] - 0.5) < 1e-6
                               and d["recall"] > 0.999)
        d["kashif"] = KASHIF.get(b)
        d["delta_vs_kashif"] = (d["acc_mean"] - d["kashif"]
                                if d["kashif"] else None)
    return best


def main() -> int:
    best = best_per_backbone()
    (RESULTS / "a0_backbones.json").write_text(
        json.dumps(best, indent=2), encoding="utf-8")

    L = ["# A0 backbone comparison (validation partition)", "",
         "Generated by `src/a0_table.py` from `results/all_runs.csv`. "
         "Mean over 3 tuning seeds at each backbone's best learning rate.",
         "",
         f"- Majority-class base rate on the validation partition: "
         f"**{BASE_RATE:.4f}** (41/62)",
         "- Kashif et al. (2026) Table 3 used a different split and "
         "protocol, so the comparison is contextual, not like-for-like.",
         "",
         "| backbone | opt | lr | our val acc | bal. acc | AUC | recall | "
         "Kashif | delta |",
         "|---|---|---|---|---|---|---|---|---|"]
    for b in ORDER:
        d = best.get(b)
        if not d:
            continue
        k = f"{d['kashif']:.4f}" if d["kashif"] else "--"
        dl = (f"{d['delta_vs_kashif']:+.4f}"
              if d["delta_vs_kashif"] is not None else "--")
        mark = " **(degenerate)**" if d["degenerate"] else ""
        L.append(
            f"| {b}{mark} | {d['optimizer']} | {d['learning_rate']:.0e} | "
            f"{d['acc_mean']:.4f} ± {d['acc_sd']:.4f} | {d['bal_acc']:.4f} | "
            f"{d['auc']:.4f} | {d['recall']:.3f} | {k} | {dl} |")

    deg = [b for b, d in best.items() if d["degenerate"]]
    L += ["", "## Degenerate arms", ""]
    if deg:
        L += [f"**{', '.join(sorted(deg))}** collapsed to a constant "
              "majority-class predictor: balanced accuracy exactly 0.5, "
              "recall 1.000, and zero variance across every seed and "
              "learning rate. Their accuracy figure is the base rate "
              f"({BASE_RATE:.4f}), not a measure of performance, and must "
              "not be tabulated beside the working backbones without this "
              "note. See DEVIATIONS.md D-010.", ""]
    else:
        L += ["None.", ""]
    (RESULTS / "a0_backbones.md").write_text("\n".join(L), encoding="utf-8")

    # LaTeX
    T = ["% Generated by src/a0_table.py - do not edit by hand.",
         "\\begin{table}[t]", "\\centering",
         "\\caption{A0 backbone comparison on the validation partition, "
         "mean $\\pm$ SD over 3 seeds at each backbone's best learning "
         "rate. Daggered rows collapsed to a constant majority-class "
         "predictor (balanced accuracy 0.5, recall 1.0); their accuracy "
         f"is the base rate {BASE_RATE:.4f}, not performance.}}",
         "\\label{tab:a0backbones}", "\\small",
         "\\begin{tabular}{lrrrrrr}", "\\toprule",
         "Backbone & Val.\\ acc. & Bal.\\ acc. & AUC & Recall & "
         "Kashif & $\\Delta$ \\\\", "\\midrule"]
    for b in ORDER:
        d = best.get(b)
        if not d:
            continue
        nm = b.replace("_", "\\_") + ("$^\\dagger$" if d["degenerate"]
                                      else "")
        k = f"{d['kashif']:.4f}" if d["kashif"] else "--"
        dl = (f"{d['delta_vs_kashif']:+.4f}"
              if d["delta_vs_kashif"] is not None else "--")
        T.append(f"{nm} & {d['acc_mean']:.4f} $\\pm$ {d['acc_sd']:.4f} & "
                 f"{d['bal_acc']:.4f} & {d['auc']:.4f} & "
                 f"{d['recall']:.3f} & {k} & {dl} \\\\")
    T += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    (FIGS / "tab_a0_backbones.tex").write_text("\n".join(T),
                                               encoding="utf-8")

    print("wrote results/a0_backbones.md, results/a0_backbones.json, "
          "figures/tab_a0_backbones.tex")
    if deg:
        print(f"DEGENERATE (constant majority-class): {', '.join(sorted(deg))}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
