"""Phase 10: figures and tables (guide section 11).

Everything here is generated from artifacts on disk -- results/all_runs.csv,
results/stats_summary.json, results/selected_configs.json -- never from
hand-entered numbers.

Style contract:
  - vector PDF into figures/
  - colorblind-safe categorical palette, assigned per ARM in fixed order
    and never cycled (validated: CVD deltaE >= 8 on every adjacent pair)
  - error bars are SD over seeds unless stated otherwise
  - recessive grid and axes, thin marks, no chartjunk, one y-axis
  - a legend whenever >= 2 series; text in ink colors, never series colors

Run: python src/figures.py [--only tab_main fig_primary_delta ...]
"""
from __future__ import annotations

import argparse
import csv
import json
from collections import defaultdict
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt          # noqa: E402
import numpy as np                       # noqa: E402

REPO = Path(__file__).resolve().parents[1]
RESULTS = REPO / "results"
FIGS = REPO / "figures"

# Okabe-Ito, reordered so every adjacent pair clears the CVD floor.
# Validated with the dataviz palette validator (all checks pass).
ARM_COLOR = {
    "A0": "#0072B2",   # blue
    "A1": "#D55E00",   # vermillion  (control)
    "A2": "#009E73",   # bluish green (treatment)
    "A3": "#E69F00",   # orange
    "A5": "#CC79A7",   # reddish purple
    "A2p": "#56B4E9",  # sky blue
    "A4": "#0072B2",   # reuses blue; only ever shown with hatching
}
ARM_HATCH = {"A4": "//"}
INK, MUTED, GRID = "#1a1a1a", "#6b6b6b", "#d9d9d9"

DEPTH_ORDER = ["early", "mid", "late", "all"]


def style() -> None:
    plt.rcParams.update({
        "figure.dpi": 150,
        "savefig.dpi": 150,
        "pdf.fonttype": 42,          # embed TrueType, not Type3
        "ps.fonttype": 42,
        "font.family": "serif",
        "font.serif": ["Times New Roman", "DejaVu Serif"],
        "font.size": 9,
        "axes.labelsize": 9,
        "axes.titlesize": 9.5,
        "legend.fontsize": 8,
        "xtick.labelsize": 8,
        "ytick.labelsize": 8,
        "axes.edgecolor": MUTED,
        "axes.linewidth": 0.6,
        "axes.labelcolor": INK,
        "text.color": INK,
        "xtick.color": MUTED,
        "ytick.color": MUTED,
        "axes.grid": True,
        "grid.color": GRID,
        "grid.linewidth": 0.5,
        "axes.axisbelow": True,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "legend.frameon": False,
        "figure.autolayout": False,
    })


def load_runs() -> list[dict]:
    with (RESULTS / "all_runs.csv").open(encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def base_arm(tag: str) -> str:
    """Map a run's arm tag to its reporting arm.

    A2' is logged as "A2_<depth>_predicted"; a naive split on "_" would
    collapse it into A2 and silently merge the predicted-script arm with
    the oracle one.
    """
    if tag.endswith("_predicted"):
        return "A2p"
    return tag.split("_")[0]


def final_by_arm(rows: list[dict]) -> dict[str, list[dict]]:
    out: dict[str, list[dict]] = defaultdict(list)
    for r in rows:
        if r["phase"] == "final":
            out[base_arm(r["arm"])].append(r)
    return out


def msd(rows: list[dict], field: str) -> tuple[float, float]:
    v = np.array([float(r[field]) for r in rows
                  if r.get(field) not in ("", None)])
    if len(v) == 0:
        return float("nan"), float("nan")
    return float(v.mean()), float(v.std(ddof=1)) if len(v) > 1 else 0.0


# ------------------------------------------------------- tab_main.tex
def tab_main(rows: list[dict]) -> None:
    arms = final_by_arm(rows)
    if not arms:
        print("  tab_main: no final runs yet - skipped")
        return
    order = [a for a in ("A0", "A1", "A2", "A2p", "A3", "A4", "A5")
             if a in arms]
    metrics = [("acc", "Accuracy"), ("bal_acc", "Bal. acc."),
               ("prec", "Precision"), ("rec", "Recall"),
               ("f1", "$F_1$"), ("auc", "AUC")]
    # Seed count PER ARM. A single S taken from an arbitrary arm would
    # misreport every other row whenever an arm is incomplete (an arm
    # still running, or one that failed part way).
    n_by_arm = {a: len(arms[a]) for a in order}
    uniform = len(set(n_by_arm.values())) == 1
    seeds_phrase = (f"over {next(iter(n_by_arm.values()))} seeds"
                    if uniform else
                    "over the per-arm seed count $n$ given in the table")
    L = [
        "% Generated by src/figures.py - do not edit by hand.",
        "\\begin{table}[t]", "\\centering",
        "\\caption{Pooled test-set performance of every arm, mean $\\pm$ "
        "standard deviation " + seeds_phrase + " on the fixed split. "
        "Absolute values are within-dataset and are not generalisation "
        "estimates.}",
        "\\label{tab:main}",
        "\\small",
        "\\begin{tabular}{lr" + "r" * (len(metrics) + 1) + "}",
        "\\toprule",
        "Arm & $n$ & " + " & ".join(m[1] for m in metrics)
        + " & Params \\\\",
        "\\midrule",
    ]
    for arm in order:
        cells = []
        for f, _ in metrics:
            m, s = msd(arms[arm], f)
            cells.append("--" if np.isnan(m) else f"{m:.4f} $\\pm$ {s:.4f}")
        p = int(float(arms[arm][0]["n_params"]))
        L.append(f"{arm} & {n_by_arm[arm]} & " + " & ".join(cells)
                 + f" & {p:,} \\\\")
    L += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    (FIGS / "tab_main.tex").write_text("\n".join(L), encoding="utf-8")
    incomplete = {a: n for a, n in n_by_arm.items() if n != max(n_by_arm.values())}
    print(f"  wrote figures/tab_main.tex ({len(order)} arms, "
          f"n={n_by_arm})")
    if incomplete:
        print(f"  WARNING: incomplete arms {incomplete} - regenerate "
              f"once their runs finish")


# ----------------------------------------------- fig_primary_delta.pdf
def fig_primary_delta() -> None:
    p = RESULTS / "stats_summary.json"
    if not p.exists():
        print("  fig_primary_delta: no stats_summary.json - skipped")
        return
    st = json.loads(p.read_text(encoding="utf-8"))
    cp = st["co_primary"]
    keys = [("pooled_delta", "Pooled"), ("urdu_delta", "Urdu subset")]
    fig, axes = plt.subplots(1, 2, figsize=(6.9, 2.6), sharey=True)
    for ax, (k, title) in zip(axes, keys):
        r = cp[k]
        lo, hi = r["ci95"]
        m = r["mean_difference"]
        ax.axvline(0, color=MUTED, lw=0.8, ls="--", zorder=1)
        ax.errorbar([m], [0], xerr=[[m - lo], [hi - m]], fmt="o",
                    color=ARM_COLOR["A2"], ecolor=ARM_COLOR["A2"],
                    elinewidth=1.6, capsize=3.5, capthick=1.2,
                    markersize=7, zorder=3)
        dmin = st["delta_min"]
        ax.axvspan(-dmin, dmin, color=GRID, alpha=0.55, zorder=0, lw=0)
        ax.set_title(f"{title}  (S={r['S']})", pad=6)
        ax.set_yticks([])
        ax.set_xlabel("A2 $-$ A1 accuracy difference")
        ax.annotate(f"{m:+.4f}\n[{lo:+.4f}, {hi:+.4f}]", (m, 0),
                    textcoords="offset points", xytext=(0, 16),
                    ha="center", fontsize=8, color=INK)
        ax.annotate(f"$p$ = {r['p_t']:.3f}   $d_z$ = {r['dz']:+.2f}", (0.5, 0.06),
                    xycoords="axes fraction", ha="center", fontsize=7.5,
                    color=MUTED)
    axes[0].set_ylim(-0.6, 0.6)
    fig.suptitle("Co-primary endpoints: script-conditioned (A2) minus "
                 "matched control (A1)", y=1.02, fontsize=9.5)
    fig.text(0.5, -0.10, "Point = mean paired difference over seeds; bars = "
             "95% CI. Shaded band = pre-specified minimal effect "
             f"($\\pm${st['delta_min']}).", ha="center", fontsize=7.5,
             color=MUTED)
    fig.tight_layout()
    fig.savefig(FIGS / "fig_primary_delta.pdf", bbox_inches="tight")
    plt.close(fig)
    print("  wrote figures/fig_primary_delta.pdf")


# ------------------------------------------------- fig_per_script.pdf
def fig_per_script(rows: list[dict]) -> None:
    arms = final_by_arm(rows)
    show = [a for a in ("A0", "A1", "A2", "A3") if a in arms]
    if not show:
        print("  fig_per_script: no final runs yet - skipped")
        return
    scripts = [("acc_urdu", "Urdu"), ("acc_english", "English"),
               ("acc_digit", "Digits")]
    fig, ax = plt.subplots(figsize=(5.2, 2.8))
    x = np.arange(len(scripts))
    w = 0.8 / len(show)
    for i, arm in enumerate(show):
        means = [msd(arms[arm], f)[0] for f, _ in scripts]
        sds = [msd(arms[arm], f)[1] for f, _ in scripts]
        ax.bar(x + i * w - 0.4 + w / 2, means, w * 0.88, yerr=sds,
               label=arm, color=ARM_COLOR[arm], edgecolor="white",
               linewidth=0.8, error_kw=dict(elinewidth=0.9, capsize=2.2,
                                            ecolor=MUTED))
    ax.set_xticks(x)
    ax.set_xticklabels([s[1] for s in scripts])
    ax.set_ylabel("Test accuracy")
    ax.set_ylim(0, 1.0)
    ax.legend(ncol=len(show), loc="upper center",
              bbox_to_anchor=(0.5, 1.16), columnspacing=1.4,
              handlelength=1.2)
    ax.set_title("Accuracy by script", pad=22)
    fig.text(0.5, -0.06, "Error bars = SD over seeds.", ha="center",
             fontsize=7.5, color=MUTED)
    fig.tight_layout()
    fig.savefig(FIGS / "fig_per_script.pdf", bbox_inches="tight")
    plt.close(fig)
    print("  wrote figures/fig_per_script.pdf")


# ------------------------------------------------ fig_depth_sweep.pdf
def fig_depth_sweep(rows: list[dict]) -> None:
    """Tuning-phase validation accuracy vs insertion depth, A1 vs A2."""
    g: dict[tuple[str, str], list[float]] = defaultdict(list)
    for r in rows:
        if r["phase"] == "tuning" and r["arm"].startswith(("A1_", "A2_")):
            arm, depth = r["arm"].split("_")
            g[(arm, depth)].append(float(r["acc"]))
    if not g:
        print("  fig_depth_sweep: no tuning rows - skipped")
        return
    fig, ax = plt.subplots(figsize=(4.6, 2.7))
    x = np.arange(len(DEPTH_ORDER))
    for arm, off in (("A1", -0.06), ("A2", 0.06)):
        best, sd = [], []
        for d in DEPTH_ORDER:
            v = g.get((arm, d), [])
            best.append(max(v) if v else np.nan)
            sd.append(np.std(v, ddof=1) if len(v) > 1 else 0.0)
        ax.errorbar(x + off, best, yerr=sd, marker="o", markersize=5,
                    lw=1.6, capsize=2.5, capthick=0.9, elinewidth=0.9,
                    color=ARM_COLOR[arm], ecolor=ARM_COLOR[arm], label=arm)
    ax.set_xticks(x)
    ax.set_xticklabels(DEPTH_ORDER)
    ax.set_xlabel("SCA insertion depth")
    ax.set_ylabel("Validation accuracy")
    ax.legend(loc="best", handlelength=1.4)
    ax.set_title("Depth sweep (tuning phase, validation only)", pad=6)
    fig.text(0.5, -0.08, "Marker = best config at that depth; bars = SD "
             "across all runs at that depth. Tuning data, not test.",
             ha="center", fontsize=7.5, color=MUTED)
    fig.tight_layout()
    fig.savefig(FIGS / "fig_depth_sweep.pdf", bbox_inches="tight")
    plt.close(fig)
    print("  wrote figures/fig_depth_sweep.pdf")


# --------------------------------------------- fig_training_curves.pdf
def fig_training_curves(rows: list[dict], seed: int = 301) -> None:
    """Appendix: training curves, one stated seed per arm."""
    runs = REPO / "runs"
    picks = []
    for r in rows:
        if r["phase"] == "final" and int(r["seed"]) == seed:
            d = runs / f"{r['arm']}_{r['config_hash']}_{seed}" / "history.csv"
            if d.exists():
                picks.append((r["arm"].split("_")[0], d))
    if not picks:
        print("  fig_training_curves: no history for seed "
              f"{seed} - skipped")
        return
    picks = picks[:6]
    n = len(picks)
    fig, axes = plt.subplots(1, n, figsize=(1.75 * n, 2.3), sharey=True)
    axes = np.atleast_1d(axes)
    for ax, (arm, path) in zip(axes, picks):
        with path.open(encoding="utf-8") as fh:
            h = list(csv.DictReader(fh))
        ep = [int(r["epoch"]) for r in h]
        ax.plot(ep, [float(r["loss"]) for r in h], lw=1.4,
                color=ARM_COLOR.get(arm, INK), label="train")
        ax.plot(ep, [float(r["val_loss"]) for r in h], lw=1.4, ls="--",
                color=MUTED, label="val")
        ax.set_title(arm, pad=4)
        ax.set_xlabel("epoch")
    axes[0].set_ylabel("binary cross-entropy")
    axes[0].legend(loc="best", handlelength=1.4)
    fig.suptitle(f"Training curves (seed {seed})", y=1.04, fontsize=9.5)
    fig.tight_layout()
    fig.savefig(FIGS / "fig_training_curves.pdf", bbox_inches="tight")
    plt.close(fig)
    print(f"  wrote figures/fig_training_curves.pdf (seed {seed})")


# -------------------------------------------- fig_attention_maps.pdf
SCRIPT_COLOR = {"urdu": "#009E73", "english": "#D55E00",
                "digit": "#0072B2"}


def fig_attention_maps() -> None:
    """Guide section 11 item 5.

    SCA is channel attention -- the gate is a vector over channels with
    no spatial term -- so there is no spatial heat map to draw and one
    is not invented here. The figure shows the gate vectors themselves
    and the counterfactual that matters: how far the gate moves when the
    script id changes and the image is held fixed.
    """
    src = RESULTS / "attention_gates.json"
    if not src.exists():
        print("  fig_attention_maps: run src/attention_probe.py first "
              "- skipped")
        return
    D = json.loads(src.read_text(encoding="utf-8"))
    Z = np.load(RESULTS / "attention_gates.npz")
    A = Z["A2_A"]                      # (S, 3, N, C)
    scripts = ["urdu", "english", "digit"]

    prof = A.mean(axis=(0, 2))         # (3, C) mean gate per script
    order = np.argsort(prof.mean(axis=0))[::-1]
    C = prof.shape[1]

    fig, axes = plt.subplots(1, 3, figsize=(10.4, 2.9))

    # (a) gate profiles per forced script id
    ax = axes[0]
    for k, s in enumerate(scripts):
        ax.plot(np.arange(C), prof[k][order], lw=1.0,
                color=SCRIPT_COLOR[s], label=s)
    ax.set_xlabel("channel (sorted by mean gate)")
    ax.set_ylabel("gate $a_c$")
    ax.set_title("(a) Gate profile per script", pad=4)
    ax.legend(handlelength=1.4, frameon=False)

    # (b) same profiles, centred -- the script-specific part alone
    ax = axes[1]
    dev = prof - prof.mean(axis=0, keepdims=True)
    for k, s in enumerate(scripts):
        ax.plot(np.arange(C), dev[k][order], lw=0.9,
                color=SCRIPT_COLOR[s], label=s)
    ax.axhline(0, color=GRID, lw=0.8, zorder=0)
    ax.set_xlabel("channel (same order)")
    ax.set_ylabel(r"$a_c$ - mean over scripts")
    ax.set_title("(b) Script-specific deviation", pad=4)

    # (c) how big is the script effect next to the image effect
    ax = axes[2]
    pairs = [("A2", "script"), ("A2", "image"), ("A1", "script"),
             ("A1", "image")]
    for i, (arm, kind) in enumerate(pairs):
        v = Z[f"{arm}_{kind}_sd"]
        ax.scatter(np.full(len(v), i) + np.random.default_rng(0).normal(
            0, 0.055, len(v)), v, s=9, alpha=0.75,
            color=ARM_COLOR[arm], edgecolors="none", zorder=3)
        ax.plot([i - 0.22, i + 0.22], [v.mean()] * 2, color=INK, lw=1.6,
                zorder=4)
    ax.set_yscale("log")
    ax.set_xticks(range(4))
    ax.set_xticklabels(["A2\nscript", "A2\nimage", "A1\nscript",
                        "A1\nimage"])
    ax.set_ylabel("gate SD (log scale)")
    ax.set_title("(c) What moves the gate", pad=4)

    for ax in axes:
        ax.grid(True, color=GRID, lw=0.6, alpha=0.7)
        ax.set_axisbelow(True)

    ratio = D["A2"]["ratio_script_over_image"]
    fig.suptitle("SCA channel gates (A2, 30 seeds, test partition). "
                 "SCA has no spatial term, so these are channel gates, "
                 "not spatial maps.", y=1.06, fontsize=9.5)
    fig.text(0.5, -0.13,
             "Panel (c): each point is one seed. Changing the script id "
             f"while holding the image fixed moves the gate {ratio:.1%} as "
             "much as changing the image does. A1's gates cannot see the "
             "script by construction; its non-zero value is float32 "
             "round-off and is the probe's null check.",
             ha="center", va="top", fontsize=7.6, color=MUTED, wrap=True)
    fig.tight_layout()
    fig.savefig(FIGS / "fig_attention_maps.pdf", bbox_inches="tight")
    plt.close(fig)
    print(f"  wrote figures/fig_attention_maps.pdf "
          f"(script/image gate ratio = {ratio:.4f})")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", nargs="*", default=None)
    a = ap.parse_args()
    style()
    FIGS.mkdir(exist_ok=True)
    rows = load_runs()
    jobs = {
        "tab_main": lambda: tab_main(rows),
        "fig_primary_delta": fig_primary_delta,
        "fig_per_script": lambda: fig_per_script(rows),
        "fig_depth_sweep": lambda: fig_depth_sweep(rows),
        "fig_training_curves": lambda: fig_training_curves(rows),
        "fig_attention_maps": fig_attention_maps,
    }
    for name, fn in jobs.items():
        if a.only and name not in a.only:
            continue
        fn()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
